In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

C:\Users\jpinf\Anaconda3\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\jpinf\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
C:\Users\jpinf\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  stacklevel=1)
In C:\Users\jpinf\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: 
The text.latex.unicode rcparam was deprecated in Matplotlib 3.0 and will be removed in 3.2.
In C:\Users\jpinf\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: 
The savefig.frameon rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
In C:\Users\jpinf\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: 
The pgf.debug rcparam was deprecated in Matplotlib 3.0 and will be removed in 3.2.
In C:\Users\jpinf\Anaconda3\lib\site-packages\matplo

In [2]:
train = pd.read_csv('crop_yield.csv')

In [3]:
train

State_Name       Season      Crop    Area  Production  \
0      Andaman and Nicobar Islands  Kharif       Arecanut  1254.0     2000.00   
1      Andaman and Nicobar Islands  Kharif       Arecanut  1254.0     2061.00   
2      Andaman and Nicobar Islands  Whole Year   Arecanut  1258.0     2083.00   
3      Andaman and Nicobar Islands  Whole Year   Arecanut  1261.0     1525.00   
4      Andaman and Nicobar Islands  Whole Year   Arecanut  1264.7      805.85   
...                            ...          ...       ...     ...         ...   
94370                  West Bengal  Whole Year   Turmeric   270.0      166.00   
94371                  West Bengal  Whole Year   Turmeric   284.0      229.00   
94372                  West Bengal  Whole Year   Turmeric   294.0      261.00   
94373                  West Bengal  Whole Year   Turmeric   289.0      178.00   
94374                  West Bengal  Whole Year   Turmeric   289.0      378.00   

       soil_type  
0       Laterite  
1       Laterite  
2       Laterite  
3       Laterite  
4       Laterite  
...          ...  
94370      Loamy  
94371      Loamy  
94372      Loamy  
94373      Loamy  
94374      Loamy  

[94375 rows x 6 columns]

In [4]:
train.dtypes

State_Name     object
Season         object
Crop           object
Area          float64
Production    float64
soil_type      object
dtype: object

In [5]:
train.isnull().sum()

State_Name    0
Season        0
Crop          0
Area          0
Production    0
soil_type     0
dtype: int64

In [6]:
train['State_Name'].unique()

array(['Andaman and Nicobar Islands', 'Andhra Pradesh', 'Assam', 'Goa',
       'Karnataka', 'Kerala', 'Meghalaya', 'Puducherry', 'Tamil Nadu',
       'West Bengal', 'Bihar', 'Chhattisgarh', 'Dadra and Nagar Haveli',
       'Gujarat', 'Haryana', 'Madhya Pradesh', 'Maharashtra', 'Manipur',
       'Rajasthan', 'Telangana ', 'Uttar Pradesh', 'Arunachal Pradesh',
       'Himachal Pradesh', 'Jammu and Kashmir ', 'Nagaland', 'Odisha',
       'Uttarakhand', 'Mizoram', 'Punjab', 'Tripura', 'Chandigarh',
       'Jharkhand', 'Sikkim'], dtype=object)

In [10]:
train['Season'].unique()

array(['Kharif     ', 'Whole Year ', 'Rabi       ', 'Winter     ',
       'Autumn     ', 'Summer     '], dtype=object)

In [11]:
train['Crop'].unique()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 15, 12, 13, 14], dtype=object)

In [12]:
train['soil_type'].unique()

array([' Laterite', 'Clayey', ' loamy', 'Sandy ', 'Black', 'Sandy',
       'Alluvial', 'Loamy'], dtype=object)

In [13]:
plt.rcParams["figure.figsize"] = (30,15)

In [14]:
train.loc[train['Crop']=='Arecanut', 'Crop'] = 0
train.loc[train['Crop']=='Banana', 'Crop'] =1
train.loc[train['Crop']=='Dry chillies', 'Crop'] =2
train.loc[train['Crop']=='Coconut ', 'Crop'] = 3
train.loc[train['Crop']=='Cotton(lint)', 'Crop'] =4
train.loc[train['Crop']=='Dry ginger', 'Crop'] = 5
train.loc[train['Crop']=='Groundnut', 'Crop'] =6
train.loc[train['Crop']=='Maize', 'Crop'] = 7
train.loc[train['Crop']=='Moong(Green Gram)', 'Crop'] =8
train.loc[train['Crop']=='Onion', 'Crop'] = 9
train.loc[train['Crop']=='Paddy', 'Crop'] =10
train.loc[train['Crop']=='Ragi', 'Crop'] =11
train.loc[train['Crop']=='Sugarcane', 'Crop'] =12
train.loc[train['Crop']=='Tobacco', 'Crop'] =13
train.loc[train['Crop']=='Turmeric', 'Crop'] =14
train.loc[train['Crop']=='Rice', 'Crop'] =15



In [15]:
train.loc[train['soil_type']=='Sandy', 'soil_type'] = 0
train.loc[train['soil_type']=='Sandy ', 'soil_type'] = 0
train.loc[train['soil_type']=='Red', 'soil_type'] =1
train.loc[train['soil_type']=='Black', 'soil_type'] =2
train.loc[train['soil_type']=='Clayey', 'soil_type'] = 3
train.loc[train['soil_type']=='Alluvial', 'soil_type'] =4
train.loc[train['soil_type']=='Loamy', 'soil_type'] = 5
train.loc[train['soil_type']==' loamy', 'soil_type'] = 5

train.loc[train['soil_type']==' Laterite', 'soil_type'] = 6

In [16]:
train['State_Name'].unique()

array(['Andaman and Nicobar Islands', 'Andhra Pradesh', 'Assam', 'Goa',
       'Karnataka', 'Kerala', 'Meghalaya', 'Puducherry', 'Tamil Nadu',
       'West Bengal', 'Bihar', 'Chhattisgarh', 'Dadra and Nagar Haveli',
       'Gujarat', 'Haryana', 'Madhya Pradesh', 'Maharashtra', 'Manipur',
       'Rajasthan', 'Telangana ', 'Uttar Pradesh', 'Arunachal Pradesh',
       'Himachal Pradesh', 'Jammu and Kashmir ', 'Nagaland', 'Odisha',
       'Uttarakhand', 'Mizoram', 'Punjab', 'Tripura', 'Chandigarh',
       'Jharkhand', 'Sikkim'], dtype=object)

In [17]:
train.loc[train['State_Name']=='Andaman and Nicobar Islands', 'State_Name'] = 0
train.loc[train['State_Name']=='Andhra Pradesh', 'State_Name'] =1
train.loc[train['State_Name']=='Assam', 'State_Name'] =3
train.loc[train['State_Name']=='Goa', 'State_Name'] =4
train.loc[train['State_Name']=='Karnataka', 'State_Name'] =5
train.loc[train['State_Name']=='Kerala', 'State_Name'] =6
train.loc[train['State_Name']=='Meghalaya', 'State_Name'] =7
train.loc[train['State_Name']=='Puducherry', 'State_Name'] =8
train.loc[train['State_Name']=='Tamil Nadu', 'State_Name'] =9
train.loc[train['State_Name']=='West Bengal', 'State_Name'] =10
train.loc[train['State_Name']=='Bihar', 'State_Name'] =11
train.loc[train['State_Name']=='Chhattisgarh', 'State_Name'] =12
train.loc[train['State_Name']=='Dadra and Nagar Haveli', 'State_Name'] =13
train.loc[train['State_Name']=='Gujarat', 'State_Name'] =14
train.loc[train['State_Name']=='Haryana', 'State_Name'] =15
train.loc[train['State_Name']=='Madhya Pradesh', 'State_Name'] =16
train.loc[train['State_Name']=='Maharashtra', 'State_Name'] =17
train.loc[train['State_Name']=='Manipur', 'State_Name'] =18
train.loc[train['State_Name']=='Rajasthan', 'State_Name'] =19
train.loc[train['State_Name']=='Telangana ', 'State_Name'] =20
train.loc[train['State_Name']=='Uttar Pradesh', 'State_Name'] =21
train.loc[train['State_Name']=='Arunachal Pradesh', 'State_Name'] =22
train.loc[train['State_Name']=='Himachal Pradesh', 'State_Name'] =23
train.loc[train['State_Name']=='Jammu and Kashmir ', 'State_Name'] =24
train.loc[train['State_Name']=='Nagaland', 'State_Name'] =25
train.loc[train['State_Name']=='Odisha', 'State_Name'] =26
train.loc[train['State_Name']=='Uttarakhand', 'State_Name'] =27
train.loc[train['State_Name']=='Mizoram', 'State_Name'] =28
train.loc[train['State_Name']=='Punjab', 'State_Name'] =29
train.loc[train['State_Name']=='Tripura', 'State_Name'] =30
train.loc[train['State_Name']=='Chandigarh', 'State_Name'] =31
train.loc[train['State_Name']=='Jharkhand', 'State_Name'] =32
train.loc[train['State_Name']=='Sikkim', 'State_Name'] =33          











In [18]:
train['State_Name'].unique()

array([0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33],
      dtype=object)

In [19]:
train

State_Name       Season Crop    Area  Production soil_type
0              0  Kharif         0  1254.0     2000.00         6
1              0  Kharif         0  1254.0     2061.00         6
2              0  Whole Year     0  1258.0     2083.00         6
3              0  Whole Year     0  1261.0     1525.00         6
4              0  Whole Year     0  1264.7      805.85         6
...          ...          ...  ...     ...         ...       ...
94370         10  Whole Year    14   270.0      166.00         5
94371         10  Whole Year    14   284.0      229.00         5
94372         10  Whole Year    14   294.0      261.00         5
94373         10  Whole Year    14   289.0      178.00         5
94374         10  Whole Year    14   289.0      378.00         5

[94375 rows x 6 columns]

In [20]:
train['Crop'].unique()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 15, 12, 13, 14], dtype=object)

In [21]:
train['soil_type'].unique()

array([6, 3, 5, 0, 2, 4], dtype=object)

In [22]:
X=train[["State_Name","Crop","Area","soil_type"]]
y=train["Production"]

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [25]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators=16, random_state=0)
regressor.fit(X,y)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=16,
                      n_jobs=None, oob_score=False, random_state=0, verbose=0,
                      warm_start=False)

In [26]:
print(regressor.score(X,y))

0.9684092471941279


In [27]:
X

State_Name Crop    Area soil_type
0              0    0  1254.0         6
1              0    0  1254.0         6
2              0    0  1258.0         6
3              0    0  1261.0         6
4              0    0  1264.7         6
...          ...  ...     ...       ...
94370         10   14   270.0         5
94371         10   14   284.0         5
94372         10   14   294.0         5
94373         10   14   289.0         5
94374         10   14   289.0         5

[94375 rows x 4 columns]

In [28]:
y

0        2000.00
1        2061.00
2        2083.00
3        1525.00
4         805.85
          ...   
94370     166.00
94371     229.00
94372     261.00
94373     178.00
94374     378.00
Name: Production, Length: 94375, dtype: float64

In [29]:
predictionss=regressor.predict([[0,0,1254.0,6]])
pred=format(int(predictionss[0]))

In [30]:
pred

'2024'

In [31]:
2064/1254.0

1.645933014354067

In [32]:
import pickle

pickle.dump(regressor,open('yield.pkl','wb'))

In [33]:
model = pickle.load(open('yield.pkl', 'rb'))